### ISSUE TITLE
Requests needs Unicode-only output

### ISSUE THREAD

**Issue by singlerider** [singlerider/lorenzotherobot#1]
!request, when coupled with video request with non-unicode characters, such as Korean characters, etc. will provide an error message, even though the video still gets appended to the YouTube playlist.

**Comment by TehNinth** [comment]
Uh I just killed Lorenzo by nick naming a Pokemon with Japanese.
He's stopped responding, hurry.

**Comment by TehNinth** [comment]
Apparently the utf-8 saved correctly, the only issue is displaying it.
(derived from me typing !party members and the bot hanging again)
I'm really sorry, I didn't know

**Comment by singlerider** [comment]
Thanks for the comments
