### ISSUE TITLE
Get continuous integration testing setup.

### ISSUE THREAD

**Issue by theepicsnail** [singlerider/lorenzotherobot#11]
This is probably easiest to do through [travisci](http://docs.travis-ci.com/user/getting-started/)
[Here](https://github.com/hashbang/paest-server/blob/master/.travis.yml)'s an example that I did for paest-server. This is roughly what we'll want for this except it has some extra options.

**Comment by singlerider** [comment]
Will attempt to do this over the weekend @theepicsnail.

**Comment by singlerider** [comment]
Will attempt to do this over the weekend @theepicsnail.

**Comment by singlerider** [comment]
Added TravisCI

**Comment by singlerider** [comment]
Added CircleCI
