### ISSUE TITLE
Multiple, simultaneous, independent cron jobs

### ISSUE THREAD

**Issue by singlerider** [singlerider/lorenzotherobot#12]
It would make sense to keep the cron jobs separate. Right now, if one fails, it affects the other. Different intervals and options for output would be the main draws for this.

**Comment by theepicsnail** [comment]
d91d9b970573a135930f09882c5e18ded6b592be reworked cron.
f08e6ac4f912213c88b551ea21770dd9e6aaffde updated the example config.

cron should now support: functions, times, enabled, channels, all independently.
