### ISSUE TITLE
Pokemon battles need a better way to define the winner

### ISSUE THREAD

**Issue by singlerider** [singlerider/lorenzotherobot#2]
Currently, the Pokemon battle is determined solely by random chance. However, there is an associated dictionary that can be used to help better determine the outcome of the battles, based on Pokemon type.

**Comment by theepicsnail** [comment]
The pokemon battles are still done by random. 

This is the full damage algo (including the randomness!)
http://bulbapedia.bulbagarden.net/wiki/Damage#Damage_formula

When we get around to reworking the battle logic, this should be helpful.
