### ISSUE TITLE
Add higher level battle pokemon

### ISSUE THREAD

**Issue by singlerider** [singlerider/lorenzotherobot#31]
Users at higher levels request ways to level up

**Comment by Studnicky** [comment]
If you're still using the simple battle algorithm, you could start storing 'gym leader' members into the DB with strong parties to be challenged.

Aggregate user party level and generate a gym leader's party instances within a similar scale.

**Comment by singlerider** [comment]
@Studnicky I solved this by allowing battles in whispers, disregarding the current channel.
