### ISSUE TITLE
Llama stream needs to display non-UTF 8 characters

### ISSUE THREAD

**Issue by singlerider** [singlerider/lorenzotherobot#4]
"\u256f\u00b0\u25a1\u00b0\uff09\u256f\ufe35 \u253b\u2501\u253b Lets try something new." should translate to (╯°□°）╯︵ ┻━┻ Lets try something new. (╯°□°）╯

But an error message is returned because IRC doesn't like these characters.

**Comment by theepicsnail** [comment]
I added a !flip command that shows the fliptable guy. 
https://github.com/singlerider/lorenzotherobot/blob/master/src/lib/command_headers.py#L4

Python 2 unicode is kind of awful, we'd really need to be in python3 before we could have some competent unicode logic.

**Comment by harrymilne** [comment]
Unicode works fine in Python 2. You simply need to prepend 'u' to unicode strings, for example, u"this is a unicode string".

**Comment by theepicsnail** [comment]
I guess I didn't close this issue when I added the flip table guy. Marking as closed.
