### ISSUE TITLE
Recently, Twitch has switched to AWS for their Chat Server.

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#59]
The existing IRC server: irc.twitch,tv has to change to irc.chat.twitch.tv.

However, it responses the message twice in the chat. So I have temporary changed to 192.16.64.179 since it is the main chat node cluster.

**Comment by singlerider** [comment]
Merge from my branch. This started yesterday

**Comment by kyroskoh** [comment]
I saw you have blacklist table, do i need to create table for it? what is the schema for it? probably give an alter table SQL statement for existing db and edit the new schema.sql for new db.

**Comment by singlerider** [comment]
@kyroskoh I just added that. Someone abused power as a mod in a channel (the first time that's ever happened in the year this thing has been in service). After you merge these changes, simply run the bot and the table will be created for you. You don't have to do anything fancy. If you are the SUPERUSER, you have a new command to `blacklist ["add"/"remove"] [username]`, where they will no longer be acknowledged by the bot. It is impossible for you to accidentally blacklist yourself.

**Comment by singlerider** [comment]
That reminds me, I need to force the user input name for `blacklist` to `username.lower()`
