### ISSUE TITLE
[Enhancement] Plans for Generation 2 Pokemon?

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#60]
Any plans for Gen2? I am planning to input the Pokemon Gen2 stats then add to my branch.

**Comment by singlerider** [comment]
I dont really receive a lot of demand for gen 2 from my streamers. You should merge my upstream. I made some fixes lately, especially with Twitch's new AWS servers.

**Comment by kyroskoh** [comment]
May I know where you get the gen1 pokemon stats from? Probably I can do it faster on my end for gen2.

**Comment by singlerider** [comment]
http://bulbapedia.bulbagarden.net/wiki/Main_Page

I entered it in mostly by hand with some help. The hard part about these newer generations is the added gameplay mechanics and "shiny" Pokemon. I built the capabilities into the database for the most part, including all existing types and their effects.

**Comment by kyroskoh** [comment]
yeah. i saw you have built your own probability for the pokemon for each levels for each level growth stats as well as the evolution triggers with the types.
