### ISSUE TITLE
More items (such as iron, protein, etc) to increase the pokemon stats

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#64]
Add more items such as iron, protein, etc to increase pokemon stats and display it in !check items when database row for these are created.

**Comment by singlerider** [comment]
The way my database is organized, I do not have a way to permanently increase the stats for a given pokemon. Given the context of how this is played, I do not think it is the best thing to do.

**Comment by singlerider** [comment]
If you can figure out a way to do this, I'll merge it in.
