### ISSUE TITLE
[The bot can't get the updated userlist] When a user uses !battle command even his/her opponent is in the chat

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#66]
Sometimes the bot can't get the userlist when the user uses !battle command even his/her opponent is in the chat. The person needs to (or the bot has to) rejoin the chat to resolve the problem.

**Comment by singlerider** [comment]
That's Twitch's API's fault. There isn't anything I can do about that right now, but I'll brainstorm about it.

**Comment by singlerider** [comment]
Also, nobody has to rejoin the room. It updates on five minute intervals. If it doesn't work, try again in five minutes.

**Comment by kyroskoh** [comment]
I have asked the person to wait for 5mins but we have been waiting for longer than 15mins but it don't work too...

This happens to those existing users just joined the chat, they can't battle with each other.

Another test that I have tested, the new user joined the chat and caught the new pokemon and stayed for 15mins. Then !battle with the users in the chat, it doesnt work either.

**Comment by singlerider** [comment]
Here is the problem: `https://tmi.twitch.tv/group/user/curvyllama/chatters`

That endpoint is the cause. What I could do and might do tonight is figure out a way to not return an empty list, but return the last known list. Tell them to battle in whispers until I fix it.

**Comment by singlerider** [comment]
Merge my changes. They will almost certainly fix things

**Comment by kyroskoh** [comment]
I have made the changes but it is still not getting the new userlist l. Could you let me where's the checking of 5mins or cron for it?

**Comment by singlerider** [comment]
src/lib/twitch.py => cron

**Comment by kyroskoh** [comment]
Got it,

Your code is:

def user_cron(channel=None):

I should have to put as:

def user_cron(channel="testchannel"):

or 

def user_cron(channel="toiletr0llz"):

**Comment by singlerider** [comment]
No, channel gets overridden automatically

**Comment by kyroskoh** [comment]
Hey there, sometimes it won't work to execute the schedule like u said 5mins to request the update user list from Twitch API.

**Comment by singlerider** [comment]
Can you provide specific information?

**Comment by kyroskoh** [comment]
The bot doesnt seems to get the updated userlist after that... so i need to add user.cron to the config?

            (300, True, pokemon.cron),  # pokemon released every 5 minutes
            (300, True, treats.cron),  # treat handed out every 5 minutes
            (86400, True, pokemon.market_cron), # reset market every 24 hours
            (300, True, user.cron),  # updates userlist every 5 minutes <--- ?

**Comment by singlerider** [comment]
Sorry for the delayed reply, but yes, you need the user cron

**Comment by kyroskoh** [comment]
Just to check on this... I didnt see your config.py has user_cron. Did you add that in your production's pokemon bot?

**Comment by singlerider** [comment]
Yup, for each channel, include the user cron

**Comment by kyroskoh** [comment]
My settings for config.py will be something like this:


global config

import globals
import src.lib.commands.pokemon as pokemon
import src.lib.commands.treats as treats
import src.lib.twitch as twitch

channels_to_join = ['#singlerider']

for channel in channels_to_join:
    channel = channel.lstrip('#')
    globals.CHANNEL_INFO[channel] = {'caught': True, 'pokemon': ''}

config = {
    # details required to login to twitch IRC server
    'username': 'Pikachu__bot',
    # get this from http://twitchapps.com/tmi/
    'oauth_password': 'oauth:6yc3lsd1ho0jmw52vr58udcy2mqe32',

    'debug': True,
    'log_messages': True,

    'channels': channels_to_join,

    # Cron jobs.
    'cron': {
        '#singlerider': [
            # time, run, callback
            (300, True, twitch.user_cron),  # update userlist every 5 minutes
            (86400, True, pokemon.market_cron),  # reset market every 24 hours
            (60, True, pokemon.cron),  # pokemon released every 20 minutes
            (600, True, treats.cron),  # treat handed out every 10 minutes
        ],
    },
}

**Comment by singlerider** [comment]
Looks good to me

**Comment by kyroskoh** [comment]
I have added that but it doesnt seems that it has been updated every 5mins to get the updated userlist.
