### ISSUE TITLE
Add ' !sell item [item_number] ' (Probably support with quantities will be good)

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#67]
User can sell their items in their inventory to the Pokemon Shop. Probably like 50% of the original purchased price to be credited back to their treats.

For example:

1) User has 1000 treats, 2x rare candies, 1x Fire Stone.
2) User uses !sell item 1
3) User will get 1000 + (750/2) to their treats balance.

*Add the amount of quantities to sell, will be better.

**Comment by singlerider** [comment]
I do not intend to create a sell items feature

**Comment by singlerider** [comment]
The reason why is users are not supposed to be able to receive those items unless they spent their currency on them.
