### ISSUE TITLE
[Battle System] Battle won to get more treats while Lose battle will get lesser treats

### ISSUE THREAD

**Issue by kyroskoh** [singlerider/lorenzotherobot#70]
I am thinking about adding more mechanics to the pokemon battling system. Let me know what do you think.

Probably it will have the winning rate and losing rate as a range number (sort of based on !bankheist or !gamble game).

Win: random-amount * win-rate %
Lose: random-amount * lose-rate %

The thing above is just a basic algorithm to be added by the bot to both users.

**Comment by singlerider** [comment]
I don't think there should be a reward for losing a battle. I'd like to incentivize people to make strategic choices in who they choose to battle.

**Comment by kyroskoh** [comment]
From what I understand that the one who initialized the !battle will get either +1 win/lose right? So the opponent won't be get added respectively opposite from that match right?

**Comment by singlerider** [comment]
That is correct

**Comment by singlerider** [comment]
I updated the config example

**Comment by H4R15** [comment]
bye stop emailing me
