### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by theepicsnail** [singlerider/lorenzotherobot#8]
In order to make this project easier to start up for others, it needs to have a requirements.txt to list out the python depdendencies. 

https://pip.readthedocs.org/en/1.1/requirements.html

e.g. this project relies on python's requests library

Adding a requirements.txt would make the 'setup' just pip install -r requirements.txt

**Comment by singlerider** [comment]
agreed

**Comment by theepicsnail** [comment]
This was fixed as of 4098404277e2527526649f693b8b78950de30804
